name: Deploy Frontend to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

    - name: Test SSH Connection
      run: |
        echo "Testing SSH connection..."
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }} -p ${{ secrets.HOSTINGER_PORT }} "echo 'SSH connection successful!'"

    - name: Upload Build Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.HOSTINGER_PORT }}
        source: "dist/*"
        target: "${{ secrets.HOSTINGER_FRONTEND_PATH }}"
        strip_components: 1

    - name: Update Permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          cd ${{ secrets.HOSTINGER_FRONTEND_PATH }}
          chmod -R 755 . 